### ISSUE TITLE
Share code with https://github.com/jrmuizel/etw-profiler?

### ISSUE THREAD

**Issue by jrmuizel** [nico-abram/blondie#2]
I just found out about blondie and thought you might be interested in some parts of https://github.com/jrmuizel/etw-profiler/tree/main/etw-gecko

It consumes ETW files and produces profiles like: https://share.firefox.dev/32sqKU4

It uses https://crates.io/crates/pdb-addr2line instead of dbghelp to symbolicate.

**Comment by nico-abram** [comment]
etw-gecko looks really interesting! Thanks for mentioning it. Do you know if https://profiler.firefox.com is meant just for firefox/webapps (Like the landing page implies), or if it is intended to be used with arbitrary native applications?

The symbols are being resolved in [profiler-symbol-server](https://github.com/mstange/profiler-symbol-server)/[profiler-get-symbols](https://github.com/mstange/profiler-get-symbols), right? I really like how it seems to have support for symsrv symbol servers!

Currently a big part of the code for blondie is related to manually starting an ETW tracing session and getting the events. etw-gecko instead requires using `xperf` for trace collection, and then processes the etl file. I wanted to avoid depending on `xperf` for this project to make it usable without installing the Windows Performance Toolkit.

Getting rid of the dependency on dbghelp.dll would be nice, although not something I'm too worried about. Was the reason you avoided it the requirement (As mentiond in https://docs.rs/profiler-get-symbols/0.14.0/profiler_get_symbols/ ) to run in WASM? dbghelp seems to work fine in my tests, and it was pretty easy to get up and running.

Someone else suggested I could use [the DIA SDK](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2022) , but a rust-native solution like pdb-addr2line does look like a better match.

My only problem would be mapping the image files to PDB's, since I'm not using xperf I don't get `DbgIDRSDS` events with the PDB names. I'm not too sure but maybe I can just use the https://crates.io/crates/object 's [pdb_info](https://docs.rs/object/latest/object/read/pe/struct.PeFile.html#method.pdb_info) method on PE files.

All in all, I'm not sure there's much code that could be shared with specifically the code in etw-gecko (Because I'm not using xperf), but I could probably use object/pdb-addr2line . The one thing that did look useful to me is the symrv env var parsing/lookup/download code in profiler-symbol-server in [symsrv.rs](https://github.com/mstange/profiler-symbol-server/blob/master/src/symsrv.rs)

**Comment by mstange** [comment]
> Do you know if https://profiler.firefox.com is meant just for firefox/webapps (Like the landing page implies), or if it is intended to be used with arbitrary native applications?

Supporting arbitrary native applications was one of my eventual goals when I started the project, and the current maintainers are also happy to accept patches to serve that use case. For example, [here are some issues I filed](https://github.com/firefox-devtools/profiler/milestone/13) to polish off some imperfections you run into when using it with non-Firefox profiles.

> Currently a big part of the code for blondie is related to manually starting an ETW tracing session and getting the events. etw-gecko instead requires using `xperf` for trace collection, and then processes the etl file. I wanted to avoid depending on `xperf` for this project to make it usable without installing the Windows Performance Toolkit.

etw-gecko only requires xperf at the moment because that was the fastest way to get something working. Removing the xperf dependency is definitely a goal. [There's some code to make this work](https://github.com/jrmuizel/etw-profiler/blame/496481bf959fd723c7504dccf6faab0abf3d543e/etw-reader/src/lib.rs#L224) but it's not very far along yet, as far as I know.

> Getting rid of the dependency on dbghelp.dll would be nice, although not something I'm too worried about. Was the reason you avoided it the requirement (As mentiond in https://docs.rs/profiler-get-symbols/0.14.0/profiler_get_symbols/ ) to run in WASM? dbghelp seems to work fine in my tests, and it was pretty easy to get up and running.

No, WASM was not a concern - we just ended up reusing profiler-symbol-server, which I had originally created for [the macOS profiler I'm working on](https://github.com/mstange/perfrecord), and which just happens to reuse code I had written for Firefox profiling.
pdb-addr2line gives you inline stacks and good performance. I invite you to use dbghelp or the DIA SDK on a big binary like Chrome or Firefox - you'll probably end up waiting a long time for your symbol information. pdb-addr2line has been optimized for those big binaries.

> My only problem would be mapping the image files to PDB's, since I'm not using xperf I don't get `DbgIDRSDS` events with the PDB names.

Oh, those events are synthesized by xperf, and can't just be enabled by setting the right flags when starting the trace? I wonder if there are other events like that that we would need to emulate.

> I'm not too sure but maybe I can just use the https://crates.io/crates/object 's [pdb_info](https://docs.rs/object/latest/object/read/pe/struct.PeFile.html#method.pdb_info) method on PE files.

Yes, definitely, that works. It gives you the path, the guid and the age.

> The one thing that did look useful to me is the symrv env var parsing/lookup/download code in profiler-symbol-server in [symsrv.rs](https://github.com/mstange/profiler-symbol-server/blob/master/src/symsrv.rs)

That part would ideally live in its own crate. Would you like to extract it?

**Comment by nico-abram** [comment]
>  pdb-addr2line gives you inline stacks and good performance. I invite you to use dbghelp or the DIA SDK on a big binary like Chrome or Firefox - you'll probably end up waiting a long time for your symbol information. pdb-addr2line has been optimized for those big binaries.

Ouch, I didn't know they were that slow. 

> Oh, those events are synthesized by xperf, and can't just be enabled by setting the right flags when starting the trace? I wonder if there are other events like that that we would need to emulate.

That's my understanding, based on this perfview comment
https://github.com/microsoft/perfview/blob/6a02a08e0b31531de6933304fcab18be52a6708d/src/TraceEvent/Parsers/SymbolTraceEventParser.cs#L11-L20

```cpp
    /// Kernel traces have information about images that are loaded, however they don't have enough information
    /// in the events themselves to unambigously look up PDBs without looking at the data inside the images.
    /// This means that symbols can't be resolved unless you are on the same machine on which you gathered the data.
    /// 
    /// XPERF solves this problem by adding new 'synthetic' events that it creates by looking at the trace and then
    /// opening each DLL mentioned and extracting the information needed to look PDBS up on a symbol server (this 
    /// includes the PE file's TimeDateStamp as well as a PDB Guid, and 'pdbAge' that can be found in the DLLs header.
    /// 
    /// These new events are added when XPERF runs the 'merge' command (or -d flag is passed).  It is also exposed 
    /// through the KernelTraceControl.dll!CreateMergedTraceFile API.   
```

It seems there's an [API](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/createmergedtracefile) to do that (And some other post processing like mapping paths like “\Device\HarddiskVolume1\” to the MS-DOS paths like “C:\”), Although it seems to take in a filename, meaning I don't think it can work from an in-memory trace.

> Would you like to extract it?

Yes, would it be ok if I send a PR to https://github.com/mstange/profiler-symbol-server splitting that part into a separate crate with a cargo path dependency, and you can then publish that yourself (So you keep ownership) and once published you can change the path dependency to a crates io version?

**Comment by mstange** [comment]
Sure, that's a good idea!

> That's my understanding, based on this perfview comment

Ah, interesting.

**Comment by nico-abram** [comment]
v0.4 uses symsrv, object and addr2line 🎉
